package nl.johnbaaij.anywhere.addNodes;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Vibrator;
import android.util.Log;
import android.util.SparseArray;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import com.google.android.gms.vision.CameraSource;
import com.google.android.gms.vision.Detector;
import com.google.android.gms.vision.barcode.Barcode;
import com.google.android.gms.vision.barcode.BarcodeDetector;

import java.io.IOException;

import nl.johnbaaij.anywhere.R;
import nl.johnbaaij.anywhere.abstractClasses.AbstractToolbarActivity;

import static androidx.constraintlayout.widget.Constraints.TAG;

public class QRCodeScannerActivity extends AbstractToolbarActivity {

    SurfaceView surfaceView;
    CameraSource cameraSource;
    TextView textView;
    BarcodeDetector barcodeDetector;

    int testData = 0;


    private void openNodeGroupNameActivity( ){
        // TODO: build universal method with paramater -> class
        Log.d(TAG, "NodeGroupNameActivity called");
        Intent intent = new Intent(getApplicationContext(), NodeGroupNameActivity.class);
        Log.d(TAG, "created intent");


        //TODO pass real data from QR to NodeGroupNameActivity
        intent.putExtra("dataFromQR", testData);

        startActivity(intent);
        Log.d(TAG, "Started intent");
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        Log.d(TAG, "Opened class");
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_qr_code_scanner);

        // Set values
        surfaceView = (SurfaceView) findViewById(R.id.qrCodeScanner);
        final TextView button = findViewById(R.id.buttonProgress);

        textView = (TextView) findViewById(R.id.ProgressText);

        //Initialise barcode detector
        barcodeDetector = new BarcodeDetector.Builder(this).setBarcodeFormats(Barcode.QR_CODE).build();

        //Initialise camera source
        cameraSource = new CameraSource.Builder(this, barcodeDetector)
                .setRequestedPreviewSize(640, 480).setAutoFocusEnabled(true).build();



        button.setText("All nodes scanned");

        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                openNodeGroupNameActivity();

            }
        });



        // Use surface view
        // Methods autogenerated
        surfaceView.getHolder().addCallback(new SurfaceHolder.Callback() {
            @Override
            public void surfaceCreated(SurfaceHolder holder) {
                // Add camera permission to manifest

                //TODO add if else 6:54
                try {
                    cameraSource.start(holder);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }



            @Override
            public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {

            }

            @Override
            public void surfaceDestroyed(SurfaceHolder holder) {
                cameraSource.stop();
            }
        });

        // Set barcode detector
        // Methods auto generated
        barcodeDetector.setProcessor(new Detector.Processor<Barcode>() {
            @Override
            public void release() {

            }

            @Override
            public void receiveDetections(Detector.Detections<Barcode> detections) {
                // Get data
                final SparseArray<Barcode> qrCodes = detections.getDetectedItems();

                // If qr code scanned and optained data
                if(qrCodes.size() != 0){
                    textView.post(new Runnable() {
                        @Override
                        public void run() {
                            Vibrator vibrator = (Vibrator)getApplicationContext().getSystemService(Context.VIBRATOR_SERVICE);
                            vibrator.vibrate(100);
                            String scannedText = qrCodes.valueAt(0).displayValue;
                            cameraSource.stop();
                            boolean isQuantified = scannedText.indexOf("quantified") !=-1? true: false;

                            // TODO: if scannedText already exists in database: Prompt: "Do you want to reinstall/move this node" or "this node is properly installed"
                            if(isQuantified){
                                saveToDatabase(scannedText);
                                textView.setText("Installed node correctly");
                            } else{
                                textView.setText("This is not a Quantified product :)");
                            }
                            // Wait 200ms before opening camera
                            Handler handler = new Handler();
                            handler.postDelayed(new Runnable() {
                                public void run() {
                                    startCamera();
                                }
                            }, 100);
                        }
                    });
                }
            }
        });
    }

    public void startCamera(){
        Log.d(TAG, "call functie ");

        finish();
        startActivity(getIntent());
    }

    public void saveToDatabase(String scannedText){

    }
}
